### ISSUE TITLE
Getting errors on starting DistributedAuthoritySocialHub

### ISSUE THREAD

**Issue by RunninglVlan** [Unity-Technologies/com.unity.multiplayer.samples.bitesize#255] opened 2024-11-14 12:26 UTC
```
[Vivox]: Unable to initialize Vivox. 
Please ensure that a project is properly linked at "Edit > Project Settings > Services > Vivox" if you intend to use Unity Game Services. 
If you would like to use custom credentials, you can set them by creating an InitializationOptions instance, calling SetVivoxCredentials(...) on it while providing your credentials, and passing the object into UnityServices.InitializeAsync(...)
UnityEngine.Logger:LogError (string,object)
Unity.Services.Vivox.VivoxLogger:LogError (object) (at ./Library/PackageCache/com.unity.services.vivox/Runtime/SDK/Utils/VivoxLogger.cs:15)
Unity.Services.Vivox.VivoxPackageInitializer:Initialize (Unity.Services.Core.Internal.CoreRegistry) (at ./Library/PackageCache/com.unity.services.vivox/Runtime/VivoxPackageInitializer.cs:58)
Unity.Services.Core.Internal.CoreRegistryInitializer/<>c__DisplayClass3_0/<<InitializeRegistryAsync>g__InitializePackageAsync|2>d:MoveNext () (at ./Library/PackageCache/com.unity.services.core/Runtime/Core.Internal/Registry/CoreRegistryInitializer.cs:91)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder:Start<Unity.Services.Core.Internal.CoreRegistryInitializer/<>c__DisplayClass3_0/<<InitializeRegistryAsync>g__InitializePackageAsync|2>d> (Unity.Services.Core.Internal.CoreRegistryInitializer/<>c__DisplayClass3_0/<<InitializeRegistryAsync>g__InitializePackageAsync|2>d&)
Unity.Services.Core.Internal.CoreRegistryInitializer/<>c__DisplayClass3_0:<InitializeRegistryAsync>g__InitializePackageAsync|2 (Unity.Services.Core.Internal.IInitializablePackage)
Unity.Services.Core.Internal.CoreRegistryInitializer/<>c__DisplayClass3_0/<<InitializeRegistryAsync>g__TryInitializePackageAsync|0>d:MoveNext () (at ./Library/PackageCache/com.unity.services.core/Runtime/Core.Internal/Registry/CoreRegistryInitializer.cs:63)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder:Start<Unity.Services.Core.Internal.CoreRegistryInitializer/<>c__DisplayClass3_0/<<InitializeRegistryAsync>g__TryInitializePackageAsync|0>d> (Unity.Services.Core.Internal.CoreRegistryInitializer/<>c__DisplayClass3_0/<<InitializeRegistryAsync>g__TryInitializePackageAsync|0>d&)
Unity.Services.Core.Internal.CoreRegistryInitializer/<>c__DisplayClass3_0:<InitializeRegistryAsync>g__TryInitializePackageAsync|0 (Unity.Services.Core.Internal.IInitializablePackage)
Unity.Services.Core.Internal.CoreRegistryInitializer/<InitializeRegistryAsync>d__3:MoveNext () (at ./Library/PackageCache/com.unity.services.core/Runtime/Core.Internal/Registry/CoreRegistryInitializer.cs:48)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1<System.Collections.Generic.List`1<Unity.Services.Core.Internal.PackageInitializationInfo>>:Start<Unity.Services.Core.Internal.CoreRegistryInitializer/<InitializeRegistryAsync>d__3> (Unity.Services.Core.Internal.CoreRegistryInitializer/<InitializeRegistryAsync>d__3&)
Unity.Services.Core.Internal.CoreRegistryInitializer:InitializeRegistryAsync ()
Unity.Services.Core.Internal.UnityServicesInternal/<>c__DisplayClass32_0/<<InitializeServicesAsync>g__InitializePackagesAsync|1>d:MoveNext () (at ./Library/PackageCache/com.unity.services.core/Runtime/Core.Internal/UnityServicesInternal.cs:170)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder:Start<Unity.Services.Core.Internal.UnityServicesInternal/<>c__DisplayClass32_0/<<InitializeServicesAsync>g__InitializePackagesAsync|1>d> (Unity.Services.Core.Internal.UnityServicesInternal/<>c__DisplayClass32_0/<<InitializeServicesAsync>g__InitializePackagesAsync|1>d&)
Unity.Services.Core.Internal.UnityServicesInternal/<>c__DisplayClass32_0:<InitializeServicesAsync>g__InitializePackagesAsync|1 ()
Unity.Services.Core.Internal.UnityServicesInternal/<InitializeServicesAsync>d__32:MoveNext () (at ./Library/PackageCache/com.unity.services.core/Runtime/Core.Internal/UnityServicesInternal.cs:151)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder:Start<Unity.Services.Core.Internal.UnityServicesInternal/<InitializeServicesAsync>d__32> (Unity.Services.Core.Internal.UnityServicesInternal/<InitializeServicesAsync>d__32&)
Unity.Services.Core.Internal.UnityServicesInternal:InitializeServicesAsync ()
Unity.Services.Core.Internal.UnityServicesInternal/<InitializeAsync>d__27:MoveNext () (at ./Library/PackageCache/com.unity.services.core/Runtime/Core.Internal/UnityServicesInternal.cs:80)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder:Start<Unity.Services.Core.Internal.UnityServicesInternal/<InitializeAsync>d__27> (Unity.Services.Core.Internal.UnityServicesInternal/<InitializeAsync>d__27&)
Unity.Services.Core.Internal.UnityServicesInternal:InitializeAsync (Unity.Services.Core.InitializationOptions)
Unity.Services.Core.UnityServices/<InitializeAsync>d__21:MoveNext () (at ./Library/PackageCache/com.unity.services.core/Runtime/Core/UnityServices.cs:128)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder:Start<Unity.Services.Core.UnityServices/<InitializeAsync>d__21> (Unity.Services.Core.UnityServices/<InitializeAsync>d__21&)
Unity.Services.Core.UnityServices:InitializeAsync (Unity.Services.Core.InitializationOptions)
Unity.Services.Core.UnityServices:InitializeAsync () (at ./Library/PackageCache/com.unity.services.core/Runtime/Core/UnityServices.cs:79)
Unity.Multiplayer.Samples.SocialHub.Services.ServicesHelper/<Start>d__6:MoveNext () (at Assets/Scripts/Services/ServicesHelper.cs:32)
System.Runtime.CompilerServices.AsyncVoidMethodBuilder:Start<Unity.Multiplayer.Samples.SocialHub.Services.ServicesHelper/<Start>d__6> (Unity.Multiplayer.Samples.SocialHub.Services.ServicesHelper/<Start>d__6&)
Unity.Multiplayer.Samples.SocialHub.Services.ServicesHelper:Start ()
```
```
UnityProjectNotLinkedException: To use Unity's dashboard services, you need to link your Unity project to a project ID. To do this, go to Project Settings to select your organization, select your project and then link a project ID. You also need to make sure your organization has access to the required products. Visit https://dashboard.unity3d.com to sign up.
Unity.Services.Core.Registration.CorePackageInitializer.InitializeComponents () (at ./Library/PackageCache/com.unity.services.core/Runtime/Registration/CorePackageInitializer.cs:129)
Unity.Services.Core.Internal.CoreRegistryInitializer+<>c__DisplayClass3_0.<InitializeRegistryAsync>g__InitializePackageAsync|2 (Unity.Services.Core.Internal.IInitializablePackage package) (at ./Library/PackageCache/com.unity.services.core/Runtime/Core.Internal/Registry/CoreRegistryInitializer.cs:91)
Unity.Services.Core.Internal.CoreRegistryInitializer+<>c__DisplayClass3_0.<InitializeRegistryAsync>g__TryInitializePackageAsync|0 (Unity.Services.Core.Internal.IInitializablePackage package) (at ./Library/PackageCache/com.unity.services.core/Runtime/Core.Internal/Registry/CoreRegistryInitializer.cs:63)
Rethrow as AggregateException: One or more errors occurred. (To use Unity's dashboard services, you need to link your Unity project to a project ID. To do this, go to Project Settings to select your organization, select your project and then link a project ID. You also need to make sure your organization has access to the required products. Visit https://dashboard.unity3d.com to sign up.) (There is no component `IActionScheduler` registered. Are you missing a package?) (There is no component `IProjectConfiguration` registered. Are you missing a package?) (There is no component `IActionScheduler` registered. Are you missing a package?) (There is no component `IProjectConfiguration` registered. Are you missing a package?) (There is no component `IActionScheduler` registered. Are you missing a package?)
Rethrow as ServicesInitializationException: Some services couldn't be initialized. Look at inner exceptions to get more information.
Unity.Services.Core.Internal.CoreRegistryInitializer+<>c__DisplayClass3_0.<InitializeRegistryAsync>g__Fail|3 () (at ./Library/PackageCache/com.unity.services.core/Runtime/Core.Internal/Registry/CoreRegistryInitializer.cs:108)
Unity.Services.Core.Internal.CoreRegistryInitializer.InitializeRegistryAsync () (at ./Library/PackageCache/com.unity.services.core/Runtime/Core.Internal/Registry/CoreRegistryInitializer.cs:53)
Unity.Services.Core.Internal.UnityServicesInternal+<>c__DisplayClass32_0.<InitializeServicesAsync>g__InitializePackagesAsync|1 () (at ./Library/PackageCache/com.unity.services.core/Runtime/Core.Internal/UnityServicesInternal.cs:170)
Unity.Services.Core.Internal.UnityServicesInternal.InitializeServicesAsync () (at ./Library/PackageCache/com.unity.services.core/Runtime/Core.Internal/UnityServicesInternal.cs:156)
Unity.Services.Core.Internal.UnityServicesInternal.InitializeAsync (Unity.Services.Core.InitializationOptions options) (at ./Library/PackageCache/com.unity.services.core/Runtime/Core.Internal/UnityServicesInternal.cs:94)
Unity.Services.Core.UnityServices.InitializeAsync (Unity.Services.Core.InitializationOptions options) (at ./Library/PackageCache/com.unity.services.core/Runtime/Core/UnityServices.cs:128)
Unity.Multiplayer.Samples.SocialHub.Services.ServicesHelper.Start () (at Assets/Scripts/Services/ServicesHelper.cs:32)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) (at <321eb2db7c6d43ea8fc39b54eaca3452>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at <b5bf0c891ea345fe93688f835df32fdc>:0)
UnityEngine.UnitySynchronizationContext.Exec () (at <b5bf0c891ea345fe93688f835df32fdc>:0)
UnityEngine.UnitySynchronizationContext.ExecuteTasks () (at <b5bf0c891ea345fe93688f835df32fdc>:0)
```

**Screenshots**
![image](https://github.com/user-attachments/assets/aab00f98-fa45-43fe-ad14-6c0e818775ba)

**Environment:**
 - OS: Windows 10
 - Unity Version: 6000.0.26f1
 - Netcode for GameObjects Version: 2.1.1
 - Bitesize Samples Repository Commit: 022594f4

**Comment by fernando-cortez** [comment] 2024-11-14 15:31
Hello @RunninglVlan, in order for the sample to work as intended, you'll need to register your Unity project with an organization's cloud ID. I'll point you to this section of our [readme](https://github.com/Unity-Technologies/com.unity.multiplayer.samples.bitesize/tree/main/Basic/DistributedAuthoritySocialHub#registering-the-project-with-unity-gaming-services-ugs) that contains the links to the resources to do so.

Let us know if this resolves your issue!

**Comment by RunninglVlan** [comment] 2024-11-14 15:40
Oh, sorry, looks like I missed that.
Maybe it would be good to add this requirement to Welcome Dialogue?
![image](https://github.com/user-attachments/assets/ac466a5a-c4d2-4af2-b46a-1d870615c646)

**Comment by fernando-cortez** [comment] 2024-11-14 18:59
Good point! We'll make sure to mention it either here or through the game flow with a message.
I'll close this for now as it seems like you're unblocked otherwise!
Thanks for the feedback -- it's always appreciated.

**Closed by fernando-cortez** 2024-11-14 18:59 UTC
