### ISSUE TITLE
Client not showing FXs

### ISSUE THREAD

**Issue by charlesmccann** [Unity-Technologies/com.unity.multiplayer.samples.bitesize#13] opened 2021-05-22 05:08 UTC
Host shows explosions and other effects.  The client does not show explosion or ship damage effects.

**To Reproduce**
Play game with host and client.  Running 2020.3.9f1 with the latest pull.

**Expected behavior**
Client should have same effects as host:  explosions from shots and damage effects on ship.

**Environment (please complete the following information):**
 - OS: Windows 10
 - Unity Version:  2020.3.9f1
 - MLAPI Version: 0.1.0

**Comment by AIO1** [comment] 2021-05-30 18:29
Yes, I just downloaded and tested the project and I can confirm that I'm seeing the same behaviour.

The behaviour of the bullet not spawning the fx is because it is not present in the object pool and in the line 40 of bullet.cs you can see the explosion is being instantiated with Instantiate instead of m_ObjectPool.GetNetworkObject, that’s why the explosion is not being passed to the server.

I think that might be the issue...

**Comment by LukeStampfli** [comment] 2021-08-03 18:43
The explosion spawning issue has been fixed by #24. This is currently in our develop branch and will be part of the next release.

I can confirm that the damage effects on the ship are broken and we will look into fixing them.

**Comment by LukeStampfli** [comment] 2021-08-31 13:21
Damage effects are now fixed as well in the develop branch. These changes will be part of the next release. Closing this.

**Closed by LukeStampfli** 2021-08-31 13:21 UTC
Labels: bug
